### ISSUE TITLE
Settings/ Save Server Settings doesn't seem to be saving the PI WebAPI Host

### ISSUE THREAD

**Issue by terris-anylog** [xompass/xompass-pi-webapi-browser#2] opened 2019-07-21 23:13 UTC
When I save the settings and restart the service, the console contains messages like:

Credentials Loaded:  { user: 'hidden', pass: 'hidden', sendImmediately: true }
Express Server listening on port: 7400
Uncaught: ECONNRESET en Xompass Analysis Service :
Error: Client network socket disconnected before secure TLS connection was established

I did some hacking in interface.js and srvConfig.webapi_host is undefined.

**Comment by yuyomagico** [comment] 2019-07-21 23:29
What url are you using for the webapi?

**Comment by yuyomagico** [comment] 2019-07-21 23:30
Oh I know what the problem is. Tomorrow should be resolved. Seems like the
IP changed for the server so tomorrow the DNS will be fixed. Try using the
settings on the default_config.js file

**Closed** 2019-07-25 21:06 UTC
